#!/bin/bash
if [ "$1" = "" ]; then
	echo "Please input resolution,"
	echo "Such as: qvga, wqvga, wvga, hvga, qhd"
	exit
fi
p=$1
./tool/bmp_to_raw ./temp0.raw ./$p/"${p}_uboot".bmp
./tool/bmp_to_raw ./temp1.raw ./$p/"${p}_battery".bmp
./tool/bmp_to_raw ./temp2.raw ./$p/"${p}_low_battery".bmp
./tool/bmp_to_raw ./temp3.raw ./$p/"${p}_charger_ov".bmp
#lenovo-sw lincl1  add  picture full battery 2012-5-14
./tool/bmp_to_raw ./temp4.raw ./$p/"${p}_full_battery".bmp
./tool/bmp_to_raw ./boot_logo ./$p/"${p}_kernel".bmp
#lenovo-sw jixj 2012.3.8 modified begin
#./tool/zpipe -l 9 ./"${p}.raw" temp0.raw temp1.raw temp2.raw temp3.raw
#rm -rf ./temp0.raw ./temp1.raw ./temp2.raw ./temp3.raw ./bootlogo.raw
./tool/bmp_to_raw ./temp5.raw ./$p/"${p}_factory".bmp
./tool/bmp_to_raw ./temp6.raw ./$p/"${p}_meta".bmp
#lenovo-sw weiweij modified 20120625
./tool/bmp_to_raw ./temp7.raw ./$p/"${p}_charging1".bmp
./tool/bmp_to_raw ./temp8.raw ./$p/"${p}_charging2".bmp
./tool/bmp_to_raw ./temp9.raw ./$p/"${p}_charging3".bmp
./tool/bmp_to_raw ./temp10.raw ./$p/"${p}_charging4".bmp
./tool/bmp_to_raw ./temp11.raw ./$p/"${p}_charging5".bmp
./tool/bmp_to_raw ./temp12.raw ./$p/"${p}_charging6".bmp
./tool/bmp_to_raw ./temp13.raw ./$p/"${p}_charging7".bmp
./tool/zpipe -l 9 ./"${p}.raw" temp0.raw temp1.raw temp2.raw temp3.raw temp4.raw temp5.raw temp6.raw temp7.raw temp8.raw temp9.raw temp10.raw temp11.raw temp12.raw temp13.raw
rm -rf ./temp0.raw ./temp1.raw ./temp2.raw ./temp3.raw ./bootlogo.raw temp4.raw temp5.raw temp6.raw temp7.raw temp8.raw temp9.raw temp10.raw temp11.raw temp12.raw temp13.raw
#lenovo-sw weiweij modified 20120625 end
#lenovo-sw jixj 2012.3.8 modified end
echo "conversion finished"
