#ccflags-y := -I$(src)/include -I$(src)/../../common/include -I$(src)/../../common/linux/include 
obj-y += lenovo_cabc_drv.o

#KERNELDIR ?= /lib/modules/$(shell uname -r)/build
#PWD  := $(shell pwd)
#default:
#	$(MAKE) -C $(KERNELDIR) M=$(PWD) modules
	

